allowed_users = [
    {"username": "a", "password": "a"},
    {"username": "b", "password": "b"},
    {"username": "c", "password": "c"},
    {"username": "d", "password": "d"},
    {"username": "e", "password": "e"},
    {"username": "f", "password": "f"},
    {"username": "g", "password": "g"},
    {"username": "h", "password": "h"},
    {"username": "i", "password": "i"},
    {"username": "j", "password": "j"},
    {"username": "k", "password": "k"},
    {"username": "l", "password": "l"},
    {"username": "m", "password": "m"},
    {"username": "n", "password": "n"},
    {"username": "o", "password": "o"},
    {"username": "p", "password": "p"},
    {"username": "q", "password": "q"},
    {"username": "r", "password": "r"},
    {"username": "s", "password": "s"},
    {"username": "t", "password": "t"},
    {"username": "u", "password": "u"},
    {"username": "v", "password": "v"},
    {"username": "w", "password": "w"},
    {"username": "x", "password": "x"},
    {"username": "y", "password": "y"},
    {"username": "z", "password": "z"}
]
