{
 "title": "Main Dashboard",
 "description": "Main application metrics dashboard showing FastAPI, Redis, and PostgreSQL metrics",
 "tags": [ "demo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Post Transaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi\", handler=\"/transactions\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Rollback Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=\"suppliers\"}[1m])) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"suppliers\"}[1m])) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post Transaction Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"fastapi\", method=\"POST\", handler=\"/transactions\"}[1m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count per seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('second', transaction_date) AS second,\n    COUNT(*) AS transaction_count\nFROM\n    transactions\nGROUP BY\n    DATE_TRUNC('second', transaction_date)\nORDER BY\n    second;"
    }
   ]
  }
 ]
}