{
 "title": "FastAPI",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Post Transaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"fastapi\", handler=\"/transactions\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis  Activity Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"redis:9121\", cmd!~\"client.*\", cmd!~\"config.*\", cmd!=\"info\", cmd!=\"latency|latest\", cmd!~\"slowlog.*\"}[1m])) by (cmd)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Successful Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"postgres:9187\", datname=\"suppliers\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"fastapi\", method=\"POST\"}[1m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"suppliers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count per seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('second', transaction_date) AS second,\n    COUNT(*) AS transaction_count\nFROM\n    transactions\nGROUP BY\n    DATE_TRUNC('second', transaction_date)\nORDER BY\n    second;"
    }
   ]
  }
 ]
}