{
 "title": "Redis",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 * (redis_memory_used_bytes{instance=~\"redis:9121\"}  / redis_memory_max_bytes{instance=~\"redis:9121\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"redis:9121\", cmd!~\"client.*\", cmd!~\"config.*\", cmd!=\"info\", cmd!=\"latency|latest\", cmd!~\"slowlog.*\"}[1m])) by (cmd)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=\"redis:9121\", cmd!~\"client.*\", cmd!~\"config.*\", cmd!=\"info\", cmd!=\"latency|latest\", cmd!~\"slowlog.*\"}[1m])) by (cmd) != 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}